name: 'Badges Scraper'
description: 'Coleta badges e atualiza o README'
author: 'lcrochaDEV'

inputs:
# Identificação dos Usuários
  username_alura:
    description: 'Usuário da Alura'
    required: false
  username_credly:
    description: 'Usuário do Credly'
    required: false
  username_generic:
    description: 'Usuário para seção genérica'
    required: false
  badge_limit:
    description: 'Limite de badges'
    required: false
    default: '16'
# --- Novos Inputs para a seção Generic ---
  generic_url:
    description: 'URL do site genérico'
    default: ''
  xpath_a:
    description: 'XPATH para o link (href)'
    default: ''
  xpath_b:
    description: 'XPATH para a imagem (src)'
    default: ''
  xpath_c:
    description: 'XPATH para o título (text)'
    default: ''
  # Marcadores Alura (usando o que seu amigo passou no with)
  start_section_alura:
    description: 'Tag de início Alura'
    default: ''
  end_section_alura:
    description: 'Tag de fim Alura'
    default: ''
  # Marcadores Credly
  start_section_credly:
    description: 'Tag de início Credly'
    default: ''
  end_section_credly:
    description: 'Tag de fim Credly'
    default: ''
  # --- Marcadores Opcionais ---
  start_section:
    description: 'Tag de início no README'
    default: ''
  end_section:
    description: 'Tag de fim no README'
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalar e Executar
      shell: bash
      env:
        ALURA_USER: ${{ inputs.username_alura }}
        START_ALURA: ${{ inputs.start_section_alura }}
        END_ALURA: ${{ inputs.end_section_alura }}

        INPUT_NUMBER_LAST_BADGES: ${{ inputs.badge_limit }}
        GITHUB_TOKEN: ${{ github.token }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        ACTION_PATH: ${{ github.action_path }}
        
        CREDLY_USER: ${{ inputs.username_credly }}
        START_CREDLY: ${{ inputs.start_section_credly }}
        END_CREDLY: ${{ inputs.end_section_credly }}

        GENERIC_USER: ${{ inputs.username_generic }}
        URL_GENERIC: ${{ inputs.generic_url }}
        XPATH_A: ${{ inputs.xpath_a }}
        XPATH_B: ${{ inputs.xpath_b }}
        XPATH_C: ${{ inputs.xpath_c }}
        START_SECTION: ${{ inputs.start_section }}
        END_SECTION: ${{ inputs.end_section }}
      run: |
        chmod +x "$ACTION_PATH/setup_chrome.sh"
        "$ACTION_PATH/setup_chrome.sh"