name: 'Alura Badges Scraper'
description: 'Coleta badges da Alura e atualiza o README'
author: 'lcrochaDEV'

inputs:
  username:
    description: 'Seu usuário da Alura'
    required: true
  badge_limit:
    description: 'Limite de badges'
    required: false
    default: '16'
  start_marker:
    description: 'Tag de início no README'
    default: ''
  end_marker:
    description: 'Tag de fim no README'
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalar e Executar
      shell: bash
      env:
        ALURA_USER: ${{ inputs.username }}
        INPUT_NUMBER_LAST_BADGES: ${{ inputs.badge_limit }}
        GITHUB_TOKEN: ${{ github.token }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        ACTION_PATH: ${{ github.action_path }}
        START_MARKER: ${{ inputs.start_marker }}
        END_MARKER: ${{ inputs.end_marker }}
      run: |
        chmod +x "$ACTION_PATH/setup_chrome.sh"
        "$ACTION_PATH/setup_chrome.sh"