name: 'Alura Badges Scraper'
description: 'Coleta badges da Alura e atualiza o README'
author: 'lcrochaDEV'

inputs:
  username:
    description: 'Seu usuário da Alura'
    required: true
  badge_limit:
    description: 'Limite de badges'
    required: false
    default: '16'

runs:
  using: 'composite'
  steps:
    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalar e Executar
      shell: bash
      env:
        ALURA_USER: ${{ inputs.username }}
        INPUT_NUMBER_LAST_BADGES: ${{ inputs.badge_limit }}
        GITHUB_TOKEN: ${{ github.token }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        ACTION_PATH: ${{ github.action_path }}
        START_MARKER: ""
        END_MARKER: ""
      run: |
        chmod +x "${{ github.action_path }}/setup_chrome.sh"
        "${{ github.action_path }}/setup_chrome.sh"