name: Update Alura Badges

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: 1. Checkout do código
        uses: actions/checkout@v4

      - name: 2. Garantir Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 3. EXECUTAR SEU SHELL SCRIPT (Instala tudo)
        env:
          # PyGithub
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          # Dados da Alura
          ALURA_USER: ${{ secrets.ALURA_USER }}
          # Passando os marcadores via ENV conforme solicitado
          START_MARKER: "<!--START_SECTION_ALURA:badges-->"
          END_MARKER: "<!--END_SECTION_ALURA:badges-->"
          INPUT_NUMBER_LAST_BADGES: "16"
        run: |
          chmod +x setup_chrome.sh
          ./setup_chrome.sh 